# The URL the site will be built for
base_url = "https://isgin01.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# RSS
generate_feeds = true
feed_filenames = ["atom.xml"]
default_language = "en"

title="isgin01 | blog"
description="A waste of time"

# Needed for RSS
author = "isgin01"
